postgres:
  dsn: "postgres://user:password@localhost:5432/postgres?application_name=nam&sslmode=disable" # DSN for connecting to postgres

logging:
  level: info # Log level. Available levels are: debug, info, error
  filepath: "application.log" # Path to log file
  maxsize: 10 # Maximum size in megabytes of the log file
  maxbackups: 5 # Maximum number of old log files to retain
  maxage: 30 # Maximum number of days to retain old log files
  compress: true # Whether to compress old log files or not

webserver:
  enabled: true # Whether to enable webserver (with APIs) or not
  mode: debug # A mode in which to run webserver. Available modes are: debug, release
  address: "0.0.0.0:8080" # Address to bind to
  tls:
    enabled: false # Whether to enable TLS or not
    certpath: "cert.pem" # Server certificate path
    keypath: "key.pem" # Server key path

keys: # Keys used for calling healthchecks, see github issue #8
  cacerts: ""
  clientcert: ""
  clientkey: ""

services: # Here is a map of services to enable/disable
  HealthcheckService: true # Whether to enable calling health checks or not on this instance